name: CI/CD for Vercel App

on:
  push:
    branches:
      - main    # Trigger on push to main branch
  pull_request:
    branches:
      - main    # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Chọn version Node.js bạn muốn sử dụng

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test   # Thực hiện test của bạn nếu có

      - name: Build the project
        run: |
          npm run build  # Xây dựng dự án với Vite

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel_token: ${{ secrets.VERCEL_
